### ISSUE TITLE
Widget borders

### ISSUE THREAD

**Issue by ingmferrer** [sur950/any_link_preview#1]
Hello, I want to remove the widget borders (rounded, color, padding... so no borders at all). Is there anything to achieve this?

Everything else is good.

**Comment by sur950** [comment]
Hi @ingmferrer 

Thanks for using the package. Yes, it can be achieved.
Right now, I am busy other tasks. It takes a week for me to release new version.

**Comment by sur950** [comment]
Hi @ingmferrer 

I have given the control to user regarding colour, border radius, box shadow. (We had no borders in the UI)

```backgroundColor``` is the param you need to use for colour related changes.
<img width="821" alt="Screenshot 2021-02-26 at 11 59 18 AM" src="https://user-images.githubusercontent.com/46712434/109264015-47977580-782a-11eb-98a7-433c4644c8f6.png">

**Comment by ingmferrer** [comment]
Thank you
