### ISSUE TITLE
FormatException (FormatException: Unexpected extension byte (at offset 9504)) for certain valid urls

### ISSUE THREAD

**Issue by mlars84** [sur950/any_link_preview#11]
I keep hitting this `FormatException` from `convert_patch.dart` when https://www.google.com/ is the passed as the `link`. Code example: 

```
AnyLinkPreview(
  link: "https://www.google.com",
  cache: Duration(hours: 1),
  backgroundColor: Colors.grey[300],
  errorWidget: Container(
    color: Colors.grey[300],
    child: Text('Oops!'),
  ),
);
```

https://www.google.com/ is an unlikely use case and not particularly concerning, but it is concerning that AnyLinkPreview is getting stuck in a loading state rather than handling this more gracefully. I am on Flutter 2.2.2 and using any_link_preview `^2.0.0-rc`. 

If I run the example from the repo I am also getting `Web page resolution failure from:https://www.google.com Error:FormatException: Bad GBK encoding 0xd00c`. I'm assuming this is due to how the document body is being parsed and google being an outlier, but is there concern that this could be a common issue with url's?

**Comment by ghpranav** [comment]
@sur950 Removing `br` from _accept-encoding_ list of headers seems to fix this issue
https://github.com/sur950/any_link_preview/blob/5580f4779a2b4ec98ae7dcea882b03e724a88dcf/lib/web_analyzer.dart#L186

**Comment by mlars84** [comment]
> @sur950 Removing `br` from _accept-encoding_ list of headers seems to fix this issue
> https://github.com/sur950/any_link_preview/blob/5580f4779a2b4ec98ae7dcea882b03e724a88dcf/lib/web_analyzer.dart#L186

@sur950 I can confirm. Not sure

**Comment by sur950** [comment]
Hi @mlars84 Thanks for reporting the bug.

@ghpranav Could you raise a PR for the same, I will merge that instantly, Working on own product & not finding enough time for the support.

Cheers,
Suresh
