### ISSUE TITLE
Twitter Links It shows Enable Javascript ! Do we have option to enable disable javascript?

### ISSUE THREAD

**Issue by deepatavy** [sur950/any_link_preview#14]
AnyLinkPreview fail to load Twitter Links.
It is showing error widget only.

`AnyLinkPreview(
                  link: "https://www.twitter.com/FlutterDev/status/1435664264816205832",
                  borderRadius: 4,
                  backgroundColor: Colors.white,
                  removeElevation: true,
                  displayDirection: UIDirection.UIDirectionVertical,
                  showMultimedia: true,
                  bodyMaxLines: 3,
                  bodyTextOverflow: TextOverflow.ellipsis,
                  titleStyle:TextStyle(fontSize: 20),
                  bodyStyle: TextStyle(fontSize: 14),
                ),`

Title Something went wrong

Error Body
`
JavaScript is not available. We’ve detected that JavaScript is disabled in this browser. Please enable JavaScript or switch to a supported browser to continue using twitter.com. You can see a list of supported browsers in our Help Center. Help Center Terms of Service Privacy Policy Cookie Policy Imprint Ads info © 2021 Twitter, Inc. Something went wrong, but don’t fret — let’s give it another shot.`

Adding Screen shot for output reference here
![Simulator Screen Shot - iPhone 13 - 2021-10-20 at 02 13 24](https://user-images.githubusercontent.com/75555496/137987789-53cb26c0-7b1e-4ae0-a458-ac54fbf3ad4b.png)

**Comment by EjazAmir** [comment]
any solution?

**Comment by sur950** [comment]
Hi guys,

Twitter preview isn't simple. I would need to create developer portal & register the plugin there, get some developer keys which allows us officially to read the metadata for the tweets.

I can help with the implementation if there's anyone who is ready to contribute. Right now, I am fully occupied & is not actively looking into this plugin.

**Comment by sur950** [comment]
Kindly give a try with Version 2.0.4, It has breaking changes in terms of the implementation & I guess that should work for twitter cards as well.
