### ISSUE TITLE
any_link_preview 2.0.2 is not working on Flutter Web Project

### ISSUE THREAD

**Issue by persec10000** [sur950/any_link_preview#16]
any_link_preview 2.0.2 is not working on Flutter Web Project.
It shows only "Fetching data...", and doesn't show any preview image and contents.

**Comment by sur950** [comment]
Hi @persec10000 

Can you post the snippet where it is not working. 

However, I request you to check the CORS issue with the backend since I can see results for the following URL
https://www.espn.in/football/soccer-transfers/story/4163866/transfer-talk-lionel-messi-tells-barcelona-hes-more-likely-to-leave-then-stay

Thanks!

**Comment by sur950** [comment]
Hey @persec10000 

I have added a proxy URL in Version 2.0.4 which will work if you pass a CORS proxy URL.

Give a try with that & let me know if that doesn't work.

**Comment by Vlas1414** [comment]
Hi @sur950! Flutter 2.8.1, package 2.0.4 is not working with some links on web. For example from youtube, or https://speakerdeck.com/themsaid/the-power-of-laravel-queues
But it works with https://www.espn.in/football/soccer-transfers/story/4163866/transfer-talk-lionel-messi-tells-barcelona-hes-more-likely-to-leave-then-stay

**Comment by sur950** [comment]
Hey @Vlas1414 

Try adding the proxy URL that passes the pre-flight request. 
If you don't pass proxy URL that bi-passes CORS issue then no guarantee of that all the URL's will give preview in web.

**Comment by Vlas1414** [comment]
@sur950 Oh, yep. Thank you. I didn't understand this before)

**Comment by sur950** [comment]
Thanks for the confirmation @Vlas1414 
I am hoping that your issue is fixed, So closing this ticket.
Feel free to re-open the issue if you encounter any issues in the web.
