### ISSUE TITLE
Doesn't work for this url (base64 image)

### ISSUE THREAD

**Issue by pdivita** [sur950/any_link_preview#17]
This is the url I tested: [http://www.phoenicia.it/](http://www.phoenicia.it/)

I don't know if this is a problem of how the webpage is coded, but `link_view_vertical.dart` tries always to use NetworkImage, but in this case the imageUri parameter is not an uri, but a data:image in base64 format as String.

I added a momentary fix. Instad of

`image: DecorationImage(image: NetworkImage(imageUri), fit: BoxFit.cover)`

I changed it to:
`image: DecorationImage(image: img, fit: BoxFit.fitWidth,)`

where img definition is this:

```
ImageProvider img = NetworkImage(imageUri);
if(imageUri.startsWith('data:image')){
   img = MemoryImage(base64Decode(imageUri.substring(imageUri.indexOf('base64') + 7)));
}
```

Hope it helps.

Added screenshot of the code
![immagine](https://user-images.githubusercontent.com/35732152/150805021-f957237d-d55b-4a91-8344-3ff9c0fa6b46.png)

**Comment by sur950** [comment]
Hi @pdivita 

Thanks for using the package & letting us know on a fix which works one more use case. 
I will add this change in the next release.

Do share & give a star to the repo if you like it.

**Comment by sur950** [comment]
Added in version 2.0.3
