### ISSUE TITLE
Doesn't work with multiline JSON field

### ISSUE THREAD

**Issue by pdivita** [sur950/any_link_preview#18]
This URL [https://www.cucchiaio.it/ricetta/chili-con-carne/](https://www.cucchiaio.it/ricetta/chili-con-carne/)  contains a JSON with multilnes.
I know it's not good to have a multiline JSON, but for my work I need to deal with this particular case.
As for now, in `json_ld_parser.dart`, the `_parseToJson` functions calls:

`var d = jsonDecode(data);`

which make the code crash because of unexpected char.

The fix is easy: I replaced all the newlines with a space character, with:

`var d = jsonDecode(data.replaceAll('\n', ' '));`

Hope it helps

**Comment by sur950** [comment]
Thanks @pdivita 

I will add this in the next release

**Comment by sur950** [comment]
[https://github.com/sur950/any_link_preview/commit/23558f96830d5c56f8edc59d49f54d0edd4d4f7e](url)
