### ISSUE TITLE
wrong urls

### ISSUE THREAD

**Issue by Livingstone99** [sur950/any_link_preview#19]
for dynamic urls. how are wrong urls handled? because wrong links seems to break the app. I tried this link htps://asd.com and its raising at io_client.dart and also osError: OSError (OS Error: connection refused, errno = 111). pls is there a bull to check if a url is valid or not?

**Comment by sur950** [comment]
Hey @Livingstone99 

Thanks for using the package. I have added a new method `AnyLinkPreview.isValidLink()` in version 2.0.4 which allows one to verify whether the link is valid or not prior.

Hope this solves the issues. 
Also for custom UI there's a new method that is added which gives the raw data `AnyLinkPreview.getMetadata()`

Feel free to re-open the issue if the new method doesn't satisfy your use case.

Cheers,
Suresh
