### ISSUE TITLE
When will you support the web?

### ISSUE THREAD

**Issue by MCode-Team** [sur950/any_link_preview#2]

**Comment by sur950** [comment]
Hi @MCode-Team 

Thanks for using the plug-in, I was waiting for stable web release.
It is out now.

I will start making it available for both Desktop & Web. As I am busy with my work, you can expect this change in a week or two.

Cheers,
Suresh

**Comment by sur950** [comment]
Hi @MCode-Team 

Here's an update on this issue,

Currently ```dart:isolate``` & ```dart:io``` are not supported in flutter web. We might need to wait for some more time.

If you want to use it in web then the only way is removing those two dependencies (Which I don't recommend, as it will take lot time to load the preview).

If I had any updates, I will post them here.
Thanks!

**Comment by sur950** [comment]
Web support added from Version - 2.0.2

Cheers,
Suresh
