### ISSUE TITLE
urneachable pub

### ISSUE THREAD

**Issue by BenCherif** [sur950/any_link_preview#20]
i was trying to run  flutter get pub but without any success . i checked "PUB POINTS" then i found this issue 
(At the time of the analysis https://suresh-konakanchi.in/ was unreachable).

**Comment by sur950** [comment]
yah, I have seen that.

It's just the Home page which is not reachable (This is currently in work). 
This shouldn't cause any issue to perform `flutter pub get` or `flutter packages get`

I have verified this at end & seems `flutter pub get` is working as expected.

**Comment by BenCherif** [comment]
thanks sir , it works
