### ISSUE TITLE
Twitter links not working

### ISSUE THREAD

**Issue by bahaafathi** [sur950/any_link_preview#21]

**Comment by sur950** [comment]
Hey @bahaafathi 

Can you share the link which you see a failure. 
Also I recommend try with other twitter links & see if it is not working for any of them or just a specific one.

**Comment by bahaafathi** [comment]
@sur950  I have tried many Twitter links all links are not working They all don't work even the link in example "https://twitter.com/laravelphp/status/1222535498880692225"

**Comment by bahaafathi** [comment]
<img width="522" alt="Screen Shot 2022-02-02 at 1 54 38 PM" src="https://user-images.githubusercontent.com/35146824/152148962-6852dd87-c2ba-454b-b9bd-cefb2d304e8b.png">

**Comment by sur950** [comment]
Can you please share the output of `flutter doctor -v` and the package version that you were using.

I recommend to pass proxy URL if you are also using the same in web.
However, I will check why this isn't working in mobile.

**Comment by sur950** [comment]
Hey @bahaafathi 

This issue is resolved in latest version of the package. **any_link_preview: ^2.0.5**

Feel free to re-open the issue if you still face it.

Cheers,
Suresh
