### ISSUE TITLE
Option To Remove Print Statements

### ISSUE THREAD

**Issue by herrchmafi** [sur950/any_link_preview#23]
It looks like there's a number of debug logs that show up in the console. Any way we can include a flag property as part of `AnyLinkPreview` to disable these?

**Comment by sur950** [comment]
Hey @herrchmafi 

I have added your point to the list, It will be available in my immediate version.

Cheers!

**Comment by sur950** [comment]
Hey @herrchmafi 

What version of the package you were using, I see all the debug logs were commented in the latest version. I think you are old version of the plugin.

Kindly update to the latest

**Comment by herrchmafi** [comment]
@sur950 Switched over to 2.0.6! Looks like there's a couple logs in the exception handling. Any way you can update to
 handle these cases or is there something on my end (looks to be a part of the widget itself)?

Here's my console logs: ![Screen Shot 2022-02-16 at 10 34 12 AM](https://user-images.githubusercontent.com/10555443/154332872-4a485b55-8bf5-41fa-b15f-fd402e8d0c6f.png)

Thanks for responding!

**Comment by sur950** [comment]
Is the image that you are getting from meta data is valid link. Meaning, is it accessible in the browser?
