### ISSUE TITLE
Link preview does not change when providing link via text controller.

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#24]
I am pasting link in TextField and using setState to update the state but the link preview of url  does not appear/update. It shows error widget.

`code`

`class VerifyLinkUI extends StatefulWidget {
  @override
  _VerifyLinkUIState createState() => _VerifyLinkUIState();
}

class _VerifyLinkUIState extends State<VerifyLinkUI> {
  TextEditingController linkUrlController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: TextField(
            controller: linkUrlController,
            decoration: const InputDecoration(
                hintText: "Paste link of google drive,google docs,youtube etc",
                hintStyle: TextStyle(fontSize: 12)),
            onChanged: (value) {
              setState(() {
                logger.d(
                    'linkUrlController is ============= ${linkUrlController.text}');
              });
            },
          ),
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: AnyLinkPreview(
            link: linkUrlController.text,
            displayDirection: UIDirection.UIDirectionHorizontal,
            showMultimedia: true,
            bodyMaxLines: 5,
            bodyTextOverflow: TextOverflow.ellipsis,
            titleStyle: const TextStyle(
              color: Colors.black,
              fontWeight: FontWeight.bold,
              fontSize: 15,
            ),
            bodyStyle: const TextStyle(color: Colors.grey, fontSize: 12),
            errorBody: 'Show my custom error body',
            errorTitle: 'Show my custom error title',
            errorWidget: Container(
              color: Colors.grey[300],
              child: const Text('Oops!'),
            ),
            errorImage: "https://google.com/",
            cache: const Duration(days: 7),
            backgroundColor: Colors.grey[300],
            borderRadius: 0,
            removeElevation: false,
            boxShadow: const [BoxShadow(blurRadius: 3, color: Colors.grey)],
            onTap: () {}, // This disables tap event
          ),
        ),
      ],
    );
  }
}
`

**Comment by sur950** [comment]
Hey @SatyamKr07 

I suggest to verify your link prior to passing it to the LinkPreview. 
However, Let me run this & see what is the error that we are getting.

I will be releasing a new version before this weekend & you can expect a fix in the same.

Thanks mate

**Comment by sur950** [comment]
@SatyamKr07 Pass the `Key` to the LinkPreview widget & your issue will be solved.
Something like `key: Key(linkUrlController.text.toString())`

`class VerifyLinkUI extends StatefulWidget {
  @override
  _VerifyLinkUIState createState() => _VerifyLinkUIState();
}

class _VerifyLinkUIState extends State {
  TextEditingController linkUrlController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: TextField(
            controller: linkUrlController,
            decoration: const InputDecoration(
                hintText: "Paste link of google drive,google docs,youtube etc",
                hintStyle: TextStyle(fontSize: 12)),
            onChanged: (value) {
              setState(() {
                print(
                    'linkUrlController is ============= ${linkUrlController.text}');
              });
            },
          ),
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: AnyLinkPreview(
            key: Key(linkUrlController.text.toString()),
            link: linkUrlController.text,
            displayDirection: UIDirection.UIDirectionHorizontal,
            showMultimedia: true,
            bodyMaxLines: 5,
            bodyTextOverflow: TextOverflow.ellipsis,
            titleStyle: const TextStyle(
              color: Colors.black,
              fontWeight: FontWeight.bold,
              fontSize: 15,
            ),
            bodyStyle: const TextStyle(color: Colors.grey, fontSize: 12),
            errorBody: 'Show my custom error body',
            errorTitle: 'Show my custom error title',
            errorWidget: Container(
              color: Colors.grey[300],
              child: const Text('Oops!'),
            ),
            errorImage: "https://google.com/",
            cache: const Duration(days: 7),
            backgroundColor: Colors.grey[300],
            borderRadius: 0,
            removeElevation: false,
            boxShadow: const [BoxShadow(blurRadius: 3, color: Colors.grey)],
            onTap: () {}, // This disables tap event
          ),
        ),
      ],
    );
  }
}`
