### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: SocketException: Failed host lookup: 'youtue.com' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#26]
Getting this exception in debug console when using -
In the ui it should show error widget but it is showing Fetching data...

url used: https://youtue.com (Note: this site doesn't exist, it is just misspelled youtube )

Full issue pic from debug console:
![image](https://user-images.githubusercontent.com/43945413/160062156-f1210a89-1924-490d-bb9d-8e4fe0c92ef4.png)

Please handle this exception to show error widget.
Thanks

**Comment by sur950** [comment]
Hey @SatyamKr07 

Thanks for reporting this. I have added this to my bucket & will be included in the next version of the package. 

As a temporary fix, you can use try... catch with SocketException to notify error to the end user. I will try to release a new version over this weekend.

**Comment by sur950** [comment]
Now this is fixed in new version of the package. You can find the commit here: e0985e53ee88c67825f3454f4ce076f13ab760f4
