### ISSUE TITLE
Misstype code

### ISSUE THREAD

**Issue by maxakak1998** [sur950/any_link_preview#29]
These key should be the same

![image](https://user-images.githubusercontent.com/50696626/163792976-ac985c74-74c2-4d0a-b205-12297ba02c09.png)
![image](https://user-images.githubusercontent.com/50696626/163793013-0efa0119-d58a-46bc-a363-d569a72bbbf9.png)

**Comment by sur950** [comment]
Hi,

Thanks for reporting, I will add that in my next release.

**Comment by sur950** [comment]
This is added in latest version.

Kindly check here -> https://github.com/sur950/any_link_preview/commit/5290bb6f26a5943e0002e162a4dcd9b297a8745c

Thankyou.
