### ISSUE TITLE
Is there a way to increase preview image height in Vertical direction?

### ISSUE THREAD

**Issue by HariKrshnan** [sur950/any_link_preview#32]

**Comment by sur950** [comment]
Hi, Thanks for using the plugin.

Right now, I am following standard height for UI widgets, I am going to give this flexibility now. Expect this in the next version.

Thanks!

**Comment by sur950** [comment]
This is now added in latest version of the plugin

**Comment by nileshrathore** [comment]
in the latest update there is an option to set previewHeight that works for a full widget, is there any option to set a specific height for only preview images?
