### ISSUE TITLE
link preview error on using medium.com url

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#38]
I am getting the below error on using this url - "https://medium.com/flutter-community/a-visual-guide-to-input-decorations-for-flutter-textfield-706cf1877e25" and thus link preview is not shown.

error msg:
I/flutter (25921): Error while retrieving cache data => type 'Null' is not a subtype of type 'String'

**Comment by jl-insiders** [comment]
Look like this header is causing this page preview not to work.
       'User-Agent':
           'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)'

**Comment by jerrypaulsam** [comment]
Any solution to this issue?
