### ISSUE TITLE
type 'double' is not a subtype of type 'BorderRadiusGeometry?'

### ISSUE THREAD

**Issue by echomartha** [sur950/any_link_preview#4]
when i try to change border radius , its showing error `type 'double' is not a subtype of type 'BorderRadiusGeometry?'`

the goal is i want to make borderRadius 0

this my code 

```
   AnyLinkPreview(
                                  link: metadata,
                                  titleStyle: TextStyle(fontSize: 14, color: Colors.black, fontWeight: FontWeight.w400),
                                  bodyStyle: TextStyle(fontSize: 12, color: Colors.black.withOpacity(0.5)),
                                  borderRadius: 0,
                                  displayDirection: UIDirection.UIDirectionHorizontal,
                                  cache: Duration(hours: 1),
                                  bodyMaxLines: 3,
                                  boxShadow: [BoxShadow(color: kChacaYellowColor)],
                                  backgroundColor: kChacaYellowColor,
                                  errorWidget: Container(
                                    color: Colors.grey[300],
                                    child: Text('Oops!'),
                                  ),
                                  errorImage:
                                      'http://4.bp.blogspot.com/-GZEA28juPQ4/Urrv36Bp-4I/AAAAAAAAAOk/InvzgxJCr3s/s1600/error.png',
                                ),
```

thanks~

**Comment by sur950** [comment]
Hi @echomartha 

This issue is fixed in the package version 1.0.8

Thanks!

**Comment by echomartha** [comment]
Hi @sur950 Thanks for your response
when i update Package version to 1.0.8 there have issue 
`depends on any_link_preview ^1.0.8 which depends on url_launcher ^5.7.10, url_launcher ^5.7.10 is required.`

**Comment by sur950** [comment]
Hey @echomartha 

Yep, I need to use latest version of ```url_laucher``` package in-order to support this for Desktop. 

If you have any dependencies with the same package & needed to use old version of url_launcher. Let me know, I will try to find a way. (But updating url_laucher to latest version in your project might not break things).

Thanks!

**Comment by sur950** [comment]
Thanks for using it @echomartha
