### ISSUE TITLE
Why am I getting some weird images, weird titles and weird body text from links?

### ISSUE THREAD

**Issue by mycar98765** [sur950/any_link_preview#43]
I want to get image, title and body from link. However, I'm getting some weird images, weird titles and weird body text from the link.

Here is the strange result:

[![Strange result](https://i.stack.imgur.com/kS4bY.png)](https://i.stack.imgur.com/kS4bY.png)

My link:

https://www.bloomberg.com/news/articles/2022-11-15/russia-expected-to-agree-to-extend-black-sea-grain-export-deal

My code:

```
AnyLinkPreview(
  link: "https://www.bloomberg.com/news/articles/2022-11-15/russia-expected-to-agree-to-extend-black-sea-grain-export-deal",
),
```

Feel free to leave a comment if you need more information.

Why am I getting some weird images, weird titles and weird body text from links? I would appreciate any help. Thank you in advance!

**Comment by sur950** [comment]
Hi @mycar98765 

These are some default values configured in the library. You can always customise these. Please read the documentation clearly.
