### ISSUE TITLE
Is possible to choose when parse OG and when HTML?

### ISSUE THREAD

**Issue by And96** [sur950/any_link_preview#45]
How to choose if use open Graph Parser or html or other?
Some sites return wrong result

**Comment by sur950** [comment]
Hi @And96 

Right now there is no provision for choosing what parser you will need to use to extract metadata as I am traversing in the following order. When we get the results, Simply break the traversing and return the results.

```
final parsers = [
      _openGraph(document),
      _twitterCard(document),
      _jsonLdSchema(document),
      _htmlMeta(document),
      _otherParser(document),
    ];
```

Probably what I can do is give the flexibility to choose the order. Meaning, I will define 4-5 different orders and choose whatever order that is required. 
As this change is requested by very minimal people, Kindly expect some delay in accommodating the same.

Regards,
Suresh

**Comment by And96** [comment]
The problem is that some page dont return img and text.


Example:
https://www.hdblog.it/hardware/articoli/n564801/nvidia-geforce-rtx-4090-4060-prestazioni/

While, sharing link to WhatsApp or telegram on other online service i can got both text description and image.


Any ideas why?

**Comment by And96** [comment]
Confirm it dont work. It cannot decode utf8 with some sites. Solved manually parsing via external way.
