### ISSUE TITLE
version solving failed

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#5]
I am using firebase_storage legacy package which requires http ^0.12.2 and and any_link_preview required http ^0.13.0 and i am getting this error:

Because no versions of firebase_storage match >7.0.0 <8.0.0 and firebase_storage 7.0.0 depends on firebase_storage_web ^0.1.1+3, firebase_storage ^7.0.0 requires firebase_storage_web ^0.1.1+3.

Because firebase_storage_web 0.1.1+3 depends on http ^0.12.2 and no versions of firebase_storage_web match >0.1.1+3 <0.2.0, firebase_storage_web ^0.1.1+3 requires http ^0.12.2.

Thus, firebase_storage ^7.0.0 requires http ^0.12.2.
So, because app1 depends on both firebase_storage ^7.0.0 and http ^0.13.0, version solving failed.
pub get failed (1; So, because awarenett depends on both firebase_storage ^7.0.0 and http ^0.13.0, version solving failed.)
exit code 1

**Comment by sur950** [comment]
Hi @SatyamKr07 

Can you give a try with 1.0.8 version of the package. If that doesn't work, Can you share the snippet of the code where I can test & fix the issue.

Thanks!

**Comment by SatyamKr07** [comment]
Hey, thanks! 1.0.8 version works fine! 
Though i got conflict :-
"Because any_link_preview 1.0.8 depends on url_launcher ^5.7.10 and no versions of any_link_preview match >1.0.8 <2.0.0, any_link_preview ^1.0.8 requires url_launcher ^5.7.10. 
So, because app1 depends on both url_launcher ^6.0.3 and any_link_preview ^1.0.8, version solving failed."

I just changed my url_launcher version from ^6.0.3 to ^5.7.10 and the confilct resolved.

Thanks for resolving it!

**Comment by sur950** [comment]
Thanks for confirming @SatyamKr07
