### ISSUE TITLE
Crashes, when parsing fails for image with is not a network image or something else

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [sur950/any_link_preview#50]
https://github.com/sur950/any_link_preview/blob/a47f45237905fd802979d3572ceb75c3dc9726d3/lib/src/helpers/link_preview.dart#L336

If the parsing for the image fails, then no error image is displayed.

**Comment by sur950** [comment]
Hi @mariomurrent-softwaresolutions, 

This is fixed now and will be available from 3.0.1

**Comment by mariomurrent-softwaresolutions** [comment]
Awesome thanks
