### ISSUE TITLE
Preview function aren't working with ZOZOTOWN URL

### ISSUE THREAD

**Issue by hashikami** [sur950/any_link_preview#51]
I'm trying to open a ZOZOTOWN preview but it doesn't work.

My code
```
AnyLinkPreview(
       link: "https://zozo.jp/shop/futierlandandsasa/goods-sale/46114752/?did=75805438&rid=1093",
)
```

I can view the preview correctly on other sites, but this link does not show the preview.
Please advise!

**Comment by sur950** [comment]
Hi,

[any_link_preview: ^3.0.2](https://pub.dev/packages/any_link_preview) is Live now.

Give it a try with the latest version & let me know if you face any issues.

**Comment by sur950** [comment]
I am hoping this has been fixed on the last version. So closing it.

Feel free to open new bug if you still face the same issue.
