### ISSUE TITLE
Feature Request: onError callback

### ISSUE THREAD

**Issue by osheron** [sur950/any_link_preview#53]
I think a decent amount of my personal friction with using the library could be removed if the onus of error handling was moved onto the consuming developer from the library itself.

- I'm seeing error logging in my monitoring tool from the NetworkImage not being able to load content, which is giving me false positives
- I want to be able to choose exactly how my error is presented using language of the error itself
- I want to be able to determine what I actually consider is a true error based on the content of the error

Proposed change:
- AnyLinkPreview has a property that is: `Widget Function(Context, Metadata, Error) onError;` , that returns a widget to be displayed in the event of a caught exception. 
-- Personally, I think this would trump the need for errorImage, errorBody, errorTitle, and errorWidget, but I recognize that backwards compatibility wins.

**Comment by sur950** [comment]
Hi @osheron 

I didn't get your proposed solution. 
If you are asking to add `onError` Widget, It's already available.
If you are asking to remove the other props and use onError Widget for all sorts of errors including caught & uncaught, That makes sense.

**Comment by sur950** [comment]
Since there's no response after the last query, I am closing this request. Feel free to open he ticket or new one if you face some issue. Thanks!

**Comment by Osebest** [comment]
I am having an issue here as well, I have seen there is a Error widget, but I am in need of a "onError" function, that allows me to write a check in case the links fails.

**Comment by MichaelM-ZGuy** [comment]
Just to add my two cents: AFAIK there is no way to 'see' the error, which makes debugging difficult. If there was an `onError` function, it could be used to log the error, as a first step to debugging.
