### ISSUE TITLE
Provide support for SVG extension to load thumbnail.

### ISSUE THREAD

**Issue by jerrypaulsam** [sur950/any_link_preview#56]
Please provide support for svg images as the thumbnail fails to load with some of the websites.

**Comment by ericaliebmann** [comment]
This would be very helpful

**Comment by sur950** [comment]
Hi, This support will be available in V3.0.2

**Comment by sur950** [comment]
[any_link_preview: ^3.0.2](https://pub.dev/packages/any_link_preview) is Live now.

Feel free to open this ticket if the issue persists. Thank you!
