### ISSUE TITLE
can't parse link for Flutter web

### ISSUE THREAD

**Issue by Ashik55** [sur950/any_link_preview#59]
library working fine for flutter mobile apps but not working in flutter web.

**Comment by toco1001** [comment]
Same here.

**Comment by sudhanshun45** [comment]
any solutions for flutter web

**Comment by dennislbc** [comment]
Still a massive isssue for me

**Comment by vinayrajput05** [comment]
same here

**Comment by dennislbc** [comment]
ANYONE HAVING THE PROBLEM HERE IS THE SOLUTION.

Preface your web url's with https://corsproxy.org/? then the url. 

var webUrl = "https://corsproxy.org/?$url";

Use it in the AnyLinkPreview parameter: 
link: kIsWeb ? webUrl : url,


Problem solved.

**Comment by sunilguptasg** [comment]
Free CORS proxies eventually stop working - someone needs to pay for the service. Best to host the code as a function of a cloud server of your choice.
