### ISSUE TITLE
Twitter Links Not Loading with AnyLinkPreview.getMetadata

### ISSUE THREAD

**Issue by kornha** [sur950/any_link_preview#60]
```
final url = await reader.readValue(Formats.uri);

Metadata? metadata = url == null
                ? null
                : await AnyLinkPreview.getMetadata(link: url.uri.toString());
```

`flutter: AnyLinkPreview - Error in https://twitter.com/stats_feed/status/1705225138495513032?s=20 response (ClientException: Redirect loop detected, uri=/stats_feed/status/1705225138495513032?s=20)`

is always returning null for Twitter cards. Is this expected?

other websites works.

Twitter links work with this lib: https://pub.dev/packages/ogp_data_extract
Might it be useful to merge their functionality in?

**Comment by sur950** [comment]
Hi,

I can see the above-mentioned URL is working fine.
![Screenshot_1712583492](https://github.com/sur950/any_link_preview/assets/46712434/f3a6d0c7-60eb-4330-900c-91fd485b2e1d)


However, I suggest re-testing this in the 3.0.2 version & reopening the ticket if the issue persists.
Thanks-you!
