### ISSUE TITLE
Not showing preview for some links

### ISSUE THREAD

**Issue by devsideal** [sur950/any_link_preview#67]
Why its not showing the preview for some links? like:

https://images.app.goo.gl/3pvZjPPU6GifxQJEA
https://twitter.com/KappaCane/status/1753216494454898862

While on the other platforms (like twitter, whatsapp, etc) its showing preview.

**Comment by sur950** [comment]
Hi, I have tried with the above-mentioned links & I was able to fetch the information in the example application.

I request you to run the example application.
<img width="303" alt="Screenshot 2024-04-08 at 4 54 03 PM" src="https://github.com/sur950/any_link_preview/assets/46712434/9c66e232-5a8f-4557-a61b-0bdb6000dd74">

Also, The first link which is provided is an image link & it doesn't seem to be a valid one. 

I am closing the ticket as I can see it is working fine. Feel free to open this ticket if you face the issue after running with example code.
