### ISSUE TITLE
Dealing with null values in title and desc

### ISSUE THREAD

**Issue by dennislbc** [sur950/any_link_preview#68]
![image](https://github.com/sur950/any_link_preview/assets/53981795/1e30361d-d040-420f-92fe-860a8c3285b8)

Can I cause the errorWidget to be used when the title or desc return null like this?

**Comment by sur950** [comment]
Hi, This will be available in V 3.0.2

**Comment by sur950** [comment]
[https://pub.dev/packages/any_link_preview](any_link_preview: ^3.0.2) is Live now.

Feel free to open this ticket if the issue persists. Thank you!
