### ISSUE TITLE
Feature request: display preview using onChanged in TextField

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#7]
With static url, any_link_preview work great!
Is there a way to use it with onChanged TextField to validate a link and generate preview dynamically with change in textController.text?

**Comment by sur950** [comment]
Hi @SatyamKr07, Thanks for using the package.

I am completely occupied now. But the feature that you are requesting is possible in the current package. 
It might take some time for me (As I need dedicated time)

Thanks!

**Comment by abdullah432** [comment]
@sur950 Awesome plugin, the preview didn't change, when change URL in setstate.

**Comment by sur950** [comment]
Hi @abdullah432 

Can you share sample code where I can reproduce your issue (However, give a try with latest version of the package, which has null safety)

Thanks!

**Comment by sur950** [comment]
Since there's no response from long, Assuming the issue is no longer available in latest version of the plugin.
Closing the bug. Feel free to open new issue if you encounter the same issue again.

Cheers,
Suresh
