### ISSUE TITLE
It doesn't work Youtube link

### ISSUE THREAD

**Issue by khanhduy122** [sur950/any_link_preview#70]
example: https://www.youtube.com/watch?v=xZiTTGpRHAw

it always returns null for the YouTube link. Other links are perfect

This is my code: 

![image](https://github.com/sur950/any_link_preview/assets/88194404/51771a64-8484-49b6-9682-b53bf66f2fbf)

![image](https://github.com/sur950/any_link_preview/assets/88194404/26a4c2fe-1150-4940-8ee7-aafcadac7a4a)

**Comment by WarrenNkomanga** [comment]
for me non of the links I try are working, keep getting this error
AnyLinkPreview - Error in https://www.youtube.com/watch?v=xZiTTGpRHAw response (ClientException: XMLHttpRequest error., uri=https://www.google.com),

**Comment by sur950** [comment]
Hi,

Can you share additional details like:
- Is it happening for all YouTube links or specific
- On what Platform it is happening, Mobile(Android/IOS), Web, or Desktop(Linux/Windows/MAC)
- Were you able to see any logs in the terminal, If any please share
- Have you tried `isValidLink` and `getMetadata` methods to see if it's the same?

Thanks!

**Comment by khanhduy122** [comment]
> CHÀO,
> 
> Bạn có thể chia sẻ thêm chi tiết như:
> 
> * Điều này có xảy ra với tất cả các liên kết YouTube hoặc các liên kết cụ thể không?
> * Nó đang diễn ra trên Nền tảng nào, Di động (Android/IOS), Web hoặc Máy tính để bàn (Linux/Windows/MAC)
> * Bạn có thể xem bất kỳ nhật ký nào trong thiết bị đầu cuối không, nếu có, vui lòng chia sẻ
> * Bạn thử `isValidLink`các `getMetadata`cách xem có giống nhau không?
> 
> Cảm ơn!

Hi

- I have tried many YouTube links and they all don't work.
- This problem occurs on mobile platforms (Android, IOS).
- Here is my log when calling isValidLink and getMetadata using the link mentioned above

![image](https://github.com/sur950/any_link_preview/assets/88194404/583fa69a-ab22-4472-b9d0-9aed82866c65)

**Comment by mostafasany** [comment]
<img width="262" alt="Screenshot 2024-05-29 at 09 36 50" src="https://github.com/sur950/any_link_preview/assets/2448942/fe71170c-6847-4784-87cb-dc5b563c7d9d">
I can confirm neither Twitter or Youtube are working on  IOS or Android

**Comment by khanhduy122** [comment]
> <img alt="Ảnh chụp màn hình 2024-05-29 lúc 09 36 50" width="262" src="https://private-user-images.githubusercontent.com/2448942/334702477-fe71170c-6847-4784-87cb-dc5b563c7d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzA3NjcsIm5iZiI6MTcxNjk3MDQ2NywicGF0aCI6Ii8yNDQ4OTQyLzMzNDcwMjQ3Ny1mZTcxMTcwYy02ODQ3LTQ3ODQtODdjYi1kYzViNTYzYzdkOWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDgxNDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njk5Njg0NTg0NDM5MDUwNzJjMDI3ZmExNTIxNGUzMmY4YTkzOGJjNDllMTE4MmVjZmMzNGFiMDkwZDc3YjBmYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.65RI_WrT-uty0xSd_eC9DIHZ8qno8p7koOg1Pz6Cnhk"> Tôi có thể xác nhận rằng cả Twitter và Youtube đều không hoạt động trên iOS hoặc Android

Hello

Maybe I found the problem, you just left out the www part. is problem solved for me.

**Comment by mostafasany** [comment]
@khanhduy122 Twitter links are not shown and it hasn't `www`
https://x.com/SKGuna_writer/status/1795719760464019882
