### ISSUE TITLE
Not able to display a valid link preview.

### ISSUE THREAD

**Issue by SatyamKr07** [sur950/any_link_preview#8]
i am using this link - "https://www.brainyquote.com/topics/motivational-quotes" and it's saying opps! . You can check, it's a valid link. Also i tried displaying google forms preview and it gives error -'show your custom error body.' 

*In whatsApp I am able to see the preview though"

googel docs link : "https://forms.gle/tKgJm9A3kLrrje4j6" 
Note: "this is short url of google form. original url shows the preview of google forms but not the short url".
code snippet used:

AnyLinkPreview(
                link: "https://forms.gle/tKgJm9A3kLrrje4j6",
                // link:"https://www.brainyquote.com/topics/motivational-quotes",
                displayDirection: UIDirection.UIDirectionHorizontal,
                showMultimedia: true,
                bodyMaxLines: 5,
                bodyTextOverflow: TextOverflow.ellipsis,
                titleStyle: TextStyle(
                  color: Colors.blue,
                  fontWeight: FontWeight.bold,
                  fontSize: 15,
                ),
                bodyStyle: TextStyle(color: Colors.black, fontSize: 12),
                errorBody: 'Show my custom error body',
                errorTitle: 'Show my custom error title',
                errorWidget: Container(
                  color: Colors.grey[300],
                  child: Text('Oops'),
                ),
                errorImage: "https://google.com/",
                cache: Duration(days: 7),
                backgroundColor: Colors.blue[50],
                borderRadius: 12,
                removeElevation: true,
                // boxShadow: [BoxShadow(blurRadius: 3, color: Colors.grey)],
              ),

**Comment by sur950** [comment]
Hi @SatyamKr07 

Thanks for using the plugin. I would like to bring to your notice that there's few url's which are restricted & preview might not work. (Like Twitter, any link without metadata, Google form with limited access etc.)

Whatsapp has powerful link preview system where almost all kinds of links show preview where as same link might not show preview in other professional chat applications like Slack, Skype, Teams etc.

However, let me try with the above mentioned links & comeback again on what exactly is happening.

Thanks!

**Comment by SatyamKr07** [comment]
hey @sur950 , any updates on this?

**Comment by sur950** [comment]
Hi @SatyamKr07 

I am fully occupied with the things. I am calling out some community members to help fix this minor bug.
Thanks!

**Comment by sur950** [comment]
Hey @SatyamKr07 

Now with latest version, It is working fine. Feel free to re-open the issue if the issue still exists.

**Comment by SatyamKr07** [comment]
Thanks a lot! You rock @sur950 🙌
